core/rails/config/routes.rb
# Copyright 2013-4, Dell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
Rebar::Application.routes.draw do

  # UI scope

  # special case items that allow IDs to have .s 
  constraints(:id => /.*/ ) do
    resources :nodes do
      resources :node_roles
      resources :attribs
    end
  end

  get 'bypass' => 'support#bypass', as: :bypass

  # UI resources (should generally match the API paths)
  get "annealer", :to => "node_roles#anneal", :as => :annealer
  resources :attribs
  resources :barclamps do
    get :upload
  end
  resources :deployment_roles do
    resources :node_roles
    # SHOULD BE VIA API ONLY -> REMOVE??
    put :propose
    put :commit
  end
  resources :deployments do
    resources :roles
    resources :node_roles
    get :template
    # UX ONLY -> REMOVE???
    get :cohorts
    # SHOULD BE VIA API ONLY -> REMOVE??
    put :propose
    put :commit
    put :recall

  end

  get 'docs/eula' => 'docs#eula', as: :eula

  resources :groups
  resources :hammers
  resources :available_hammers
  resources :jigs
  resources :node_roles
  resources :roles
  resources :providers
  resources :capabilities
  resources :tenants
  resources :user_tenant_capabilities

  resources :interfaces
  resources :networks do
    resources :network_ranges
    resources :network_routers
    # special views
  end
  resources :network_ranges
  resources :network_routers
  get 'network_map' => "networks#map", :as=> :network_map
  resources :dns_name_filters
  resources :dns_name_entries

  # UI only functionality to help w/ visualization
  scope 'dashboard' do
    get 'list(/:deployment)'  => 'dashboard#list', :as => :bulk_edit
    put 'list'                => 'dashboard#list', :as => :bulk_update
    get 'layercake'           => 'dashboard#layercake', :as => :layercake
    get 'families(/:id)'      => 'dashboard#families', :as => :families
  end
  
  # UI only functionality to help w/ visualization
  scope 'utils' do
    get '/'             => 'support#index', :as => :utils
    get 'i18n/:id'      => 'support#i18n', :as => :utils_i18n, :constraints => { :id => /.*/ }
    get 'marker/:id'    => 'support#marker', :as => :utils_marker
    get 'files/:id'     => 'support#index', :as => :utils_files
    get 'import(/:id)'  => 'support#import', :as => :utils_import
    get 'upload/:id'    => 'support#upload', :as => :utils_upload
    get 'restart/:id'   => 'support#restart', :as => :restart
    get 'fail'          => "support#fail"
    get 'settings'      => "support#settings", :as => :utils_settings
    put 'settings(/:id/:value)' => "support#settings_put", :as => :utils_settings_put
  end

  # UI scope - legacy methods
  scope 'support' do
    get 'logs', :controller => 'support', :action => 'logs'
    get 'get_cli', :controller => 'support', :action => 'get_cli'
  end

  devise_for :users, { :path_prefix => 'my', :module => :devise, :class_name=> 'User' }
  resources :users, :except => :new

  # API routes (must be json and must prefix v2)()
  scope :defaults => {:format => 'json'} do

    constraints(:id => /([a-zA-Z0-9\-\.\_]*)/, :api_version => /v[2-9]/) do

      # framework resources pattern (not barclamps specific)
      scope 'api' do
        match '(*session)' => "users#options", via: [:options]
        get 'license' => 'docs#eula'
        scope 'status' do
          get "nodes(/:id)" => "nodes#status", :as => :nodes_status
          get "deployments(/:id)" => "deployments#status", :as => :deployments_status
          get "matrix(/:id)" => "deployments#matrix", :as => :deployments_matrix
          get "heartbeat" => "support#heartbeat", :as => :heartbeat_status
          get "inventory(/:id)" => "inventory#index"
          match "active" => "node_roles#status", via: [:get, :put]
        end
        scope 'test' do
          put "nodes(/:id)" => "nodes#test_load_data"
        end
        scope ':api_version' do
          # These are not restful.  They poke the annealer and wait if you pass "sync=true".
          get "anneal", :to => "node_roles#anneal", :as => :anneal
          resources :attribs, :as=>:attribs_api do
            collection do
              get 'sample'
              post 'match'
            end
          end
          resources :available_hammers do
            collection do
              get 'sample'
              post 'match'
            end
          end
          resources :barclamps do
            collection do
              get 'sample'
              post 'match'
            end
          end
          resources :tenants do
            collection do
              get 'sample'
              post 'match'
            end
            resources :users
          end
          resources :capabilities do
            collection do
              get 'sample'
              post 'match'
            end
          end
          resources :user_tenant_capabilities do
            collection do
              delete "", to: :destroy
              get 'sample'
              post 'match'
            end
          end
          resources :providers do
            collection do
              get 'sample'
              post 'match'
              get 'templates'
            end
            resources :nodes
          end
          resources :deployment_roles do
            collection do
              get 'sample'
              post 'match'
            end
            resources :roles
            resources :nodes
            resources :attribs
            put :propose
            put :commit
          end
          resources :deployments do
            collection do
              get 'sample'
              post 'match'
            end
            resources :node_roles
            resources :deployment_roles
            resources :roles
            resources :nodes
            resources :attribs
            put :propose
            put :commit
            put :recall
            put :redeploy
            put :batch
          end
          resources :event_selectors do
            collection do
              get 'sample'
              post 'match'
            end
          end
          resources :event_sinks do
            collection do
              get 'sample'
              post 'match'
            end
            resources :event_selectors
          end
          resources :groups do
            resources :nodes
          end
          resources :network_ranges do
            collection do
              get 'sample'
              post 'match'
            end
            resources :network_allocations
          end
          resources :network_routers do
            collection do
              get 'sample'
              post 'match'
            end
          end
          resources :network_allocations do
            collection do
              get 'sample'
              post 'match'
            end
          end
          resources :networks do
            collection do
              get 'sample'
              post 'match'
            end
            resources :network_ranges
            resources :network_routers
            resources :network_allocations
            member do
              match 'ip', via: [:get, :post, :delete]
              post 'allocate_ip'
              delete 'deallocate_ip'
              get 'allocations'
              get 'auto_ranges/:node_id', to: :auto_ranges
            end
          end
          resources :dns_name_filters do
            collection do
              get 'sample'
              post 'match'
            end
          end
          resources :dns_name_entries do
            collection do
              get 'sample'
              post 'match'
            end
          end
          resources :interfaces
          resources :runs
          resources :jigs do
            collection do
              get 'sample'
              post 'match'
            end
            put :activate
            put :flush
          end
          resources :nodes do
            collection do
              get 'sample'
              post 'match'
              post :whoami
            end
            resources :node_roles
            resources :hammers
            resources :attribs
            resources :roles
            resources :network_allocations
            put :propose
            put :commit
            match :power, via: [:get, :put]
            put :debug
            put :undebug
            put :redeploy
            put :scrub
            get 'addresses'
          end
          resources :hammers do
            collection do
              get 'sample'
              post 'match'
            end
            post :perform
          end
          resources :node_roles do
            collection do
              get 'sample'
              post 'match'
              get 'graph'
            end
            put :retry
            put :propose
            put :commit
            get :parents
            get :children
            resources :attribs
          end
          resources :profiles
          resources :roles do
            collection do
              get 'sample'
              post 'match'
              get 'graph'
            end
            resources :attribs
            resources :deployment_roles
            resources :node_roles
            resources :nodes
          end
          resources :users do
            collection do
              get 'sample'
              post 'match'
            end
            member do
              get "start_password_reset"

core/rails/app/controllers/dashboard_controller.rb
# Copyright 2013, Dell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
class DashboardController < ApplicationController

  # GREG: FIGURE OUT THE TENANT CRAP HERE

  def layercake
    # we may want to move this into the database at some point
    taxmap = JSON::load File.open(File.join("config", "layercake.json"), 'r')
    @layers = {}
    @status = {}
    taxmap["layers"].each { |k| @layers[k]=[] }
    NodeRole.all.joins(:node,:role).select("node_roles.*,
                                      roles.name as role_name,
                                      nodes.name as node_name,
                                      nodes.alive as node_alive,
                                      nodes.available as node_available").each do |nr|
      layer = taxmap[nr.role_name] || 'apps'
      @layers[layer] << nr 
      if nr.state == NodeRole::ERROR
        @status[layer] = 'alert'
      elsif (nr.state == NodeRole::PROPOSED)
        @status[layer] = 'user' unless @status[layer] == 'alert'
      elsif nr.state != NodeRole::ACTIVE
        @status[layer] = 'system' unless @status[layer] == 'alert'
      end
    end

    respond_to do |format|
      format.html { }
      format.json { render :json => @status.to_json } # also respond to json for layercake ajax updating
    end
  end    

  def group_change
    # TODO: not used?
    node = Node.find_by_name params[:id]
    if node.nil?
      raise "Node #{params[:id]} not found.  Cannot change group" 
    else
      group = params[:group]
      if params.key? 'automatic'
        node.group=""
      else
        node.group=group
      end
      node.save
      Rails.logger.info "node #{node.name} changed its group to be #{node.group.empty? ? 'automatic' : group}."
      render :inline => "SUCCESS: added #{node.name} to #{group}.", :cache => false 
    end
  end
  

  # Bulk Edit
  def list
    if request.put?
      nodes = {}
      params.each do |k, v|
        if k.starts_with? "node:"
          parts = k.split ':'
          node = parts[1]
          area = parts[2]
          nodes[node] ||= {} 
          nodes[node][area] = v
        end
      end
      succeeded = []
      failed = []
      nodes.each do |node_name, values|
        node = Node.find_key node_name
        begin
          node.update_attributes! values
          succeeded << node.name
        rescue StandardError=>e
          Rails.logger.info "user attempted dashboard.list put for node #{node.name} raised error #{e.message}"
          failed << node.name
        end
      end
      if failed.length>0
        flash[:notice] = I18n.t('failed', :scope=>'dashboard.list', :list=>failed.join(','))
      elsif succeeded.length>0
        flash[:notice] = I18n.t('updated', :scope=>'dashboard.list', :list=>succeeded.join(','))
      end
    end
    @nodes = if params.key? :deployment
      @deployment = Deployment.find_key params[:deployment]
      @deployment.nodes.where(:system=>false)
    else
      Node.all.where(:system=>false)
    end
  end

  # group nodes into categories
  def families

    # the attribs list is passed as the ID w/ pipe delimiters
    @families = if params[:id]
      params[:id].split "|"
    else
      ['cpu_count', 'memory',  'number_of_drives']
    end
    @nodes = {}
    # this works by building a single key with all the requested attributes in order
    # that makes it easy to sort and collect like attributes
    Node.all.each do |n|
      next if n.system
      key = @families.map { |f| (n.get_attrib(f) || t("unknown")).to_s }
      @nodes[key] ||= {}
      @nodes[key][n.id] = n.name
    end
  end

end

core/rails/app/views/dashboard/_layercake.html.haml
%div.layer= t ".#{layer}"
%div.dots
  - shorten = @layers[layer].size > 20 #current_user.settings(:ui).maxdisplay # TODO in the future if this is supposed to be a setting
  - list = {} if shorten
  - @layers[layer].each do |nr|
    - unless nr.nil?
      - working = true
      - node_led = 'on' 
      - if !nr.node_available
        - node_led = (nr.node_alive ? 'reserved' : 'idle')
        - working = false
      - elsif !nr.node_alive
        - node_led = 'off'
        - working = false
      - nr_led = NodeRole::STATES[nr.state || NodeRole::ERROR]
      - nr_led = "wait" if !working and nr.state == NodeRole::TODO 
      - unless shorten
        %span.led{:style=>"float:left", :class => nr_led, 
                    :title=>"#{nr.node_name} #{nr.role_name}"}
          = link_to "&nbsp;&nbsp;&nbsp;&nbsp;".html_safe, node_role_path(nr.id)
      - else
        - list[nr_led] ||= 0
        - list[nr_led] += 1

  - if shorten
    - list.each do |led, count|
      = image_tag("icons/led/#{led}.png")
      %span= count

core/rails/app/views/dashboard/families.html.haml
- attribs = Attrib.all.sort_by{ |a| a.name }

%p{:style => 'float:right'}
  = t '.add'
  = select_tag "attrib_new", options_from_collection_for_select(attribs, "name", "name", "none"), :id=>'new_attrib'
%h1= t '.title'


%table.data.box
  %thead
    %tr
      %th= t('.count')
      - @families.each do |f|
        %th{:style => "white-space: nowrap;"}
          = link_to f, attrib_path(f)
          - ff = @families.clone.delete_if{|i| i == f}.join("|")
          = link_to image_tag("icons/delete.png"), families_path(:id=>ff)
      %th= t('.name')
  %tbody
    - @nodes.sort_by{|k, _| k}.each do |id, node|
      %tr{ :class => cycle(:odd, :even)}
        %td= node.length
        - id.each do |f|
          %td= f rescue t('na')
        %td
          - node.sort.each do |id, n|
            = link_to n, node_path(id)


:javascript

$(document).ready(function(){
  $("#new_attrib").on("change", function() {
    a = $("#new_attrib").find('option:selected').text();
    console.debug(a);
    window.location.href = "#{families_path(:id=>@families.join("|"))}|"+a;
  })
});

core/rails/app/views/dashboard/index.html.haml
%p#add_button{:style => 'float:right'}
  = text_field_tag "new_group", t('.default_new'), :size => 15
  = link_to t('.add'), "javascript:add_group();", :class => 'button', :id=>'add_button'
%h1= t('.title')

.column_100
  - unless false
    %section.box#details
      - if params.include? :nopoll
        = t '.no_polling'
      - if @node
        = render :partial => 'show'
      - else
        %p= t(".status_empty") % Node.count
        %div{ :class=>'group', :draggable=>'true', :id=>Group.find_or_create_by!(name: 'not_set', category: 'ui').id }
          =t('.drag_hint').html_safe

#nodes
  - if @groups.nil?
    = t 'no_items'
  - else
    - i = -1
    #add_group_div.column_25{:class => cb_column_class(1,4), :style=>'display:none' }
      %table.data.box{:id => "new_group_add"}
        %thead
          %tr
            %th.status
              %a{:href=>"javascript:hide_group();", :title=>t('.hide')}
                = image_tag("icons/server_add.png")
            %th{ :id=> 'new_group', :droptarget=>'true' }
              = "THIS TEXT GETS REPLACED"
        %tbody
          %tr
            %td
            %td= t('.new_drag')
    - @groups.sort.each do |group|
      - next if group.name.eql? 'not_set' and group.nodes.count == 0
      .column_25{:class => cb_column_class(i+=1,4)}
        %table.data.box{:id => "group_#{group.id}"}
          %thead
            %tr
              - if group.nodes.count == 0
                %th.status{:title => t('.remove_group')}
                  = image_tag("icons/delete.png", :title=>t('.remove_group'), :onclick=>"javascript:remove_group(#{group.id});")
              - else
                %th.status{:title => t('updating')}
                  .inline_piechart= [0, 0, 1, 0, 0]*','
              %th.group{:title=>group.description}
                - unless group[:automatic]
                  %div{ :class=>'group', :draggable=>'true', :id=>group.id }
                    = truncate(group.name, :length => 25)
                - else
                  %div{ :class=>'group', :draggable=>'true', :id=>'USE_AUTOMATIC!' }
                    %i= truncate(group.name, :length => 25)

          %tbody
            - group.nodes.each do |node|
              %tr{ :class => ["node", cycle(:odd, :even, :name => "nodes_#{i}")], :id => node.id }
                %td.status{:raw=> node.state }
                  .led{:class => node.status, :title=>t(node.status, :scope=>'status', :default=>node.status)}
                %td.name
                  %a{:href => node_path(node.id), :draggable=>'true', :title=> (node.description.nil? ? t(:not_set) : node.description), :class => 'node_details', :id => node.id}
                    = truncate(node.name, :length => 25)

.clear

:javascript
  groups = {};
  selected = '#{session[:node]}';

  function pie_title(total, ready, failed, unknown, unready, pending, building) {
    var status = "#{t :status_pie, :scope=>'dashboard.index'}";
    status = status.replace("{0}", total);
    status = status.replace("{1}", ready);
    status = status.replace("{2}", failed);
    status = status.replace("{3}", unknown);
    status = status.replace("{4}", unready+pending+building);
    return status;
  }

    // set draggable attributes
  $('a.node_details[draggable="true"]')
    .bind('dragend', function( ev ) {
      false;
    })
    .bind('dragstart', function( ev ) {
      // console.debug("dragging " + ev.target.id);
      var dt = ev.originalEvent.dataTransfer;
      // TODO make sure only a available set this!
      dt.setData("Text", ev.target.id);
    });

  // set droppable attributes using bind_drop
  $('div.group[draggable="true"]').each(function() { bind_drop($(this))} );


  function bind_drop(div) {
    // Decide whether the thing dragged in is welcome.
    div.bind('dragover', function(ev) {
        if (ev.preventDefault) ev.preventDefault(); // allows us to drop
        return false;
    });

    // Handle the final drop...
    div.bind('drop', function(ev) {
      if (ev.preventDefault) ev.preventDefault(); // allows us to drop
      var node = ev.originalEvent.dataTransfer.getData("Text");
      var group = $(this).attr('id');
      // console.debug(node + ' into ' + group );
      $.ajax({url:'/2.0/rebar/2.0/group/'+group+'/node/'+node, dataType:'json', type:"PUT",
        statusCode: { 200: function(data) { location.href = '#{dashboard_path}/'+selected; }}
      });
    });
  }

  function hide_group() {
    $('#add_group_div').attr('style','display:none');
  }

  function remove_group(id) {
    $.ajax({url:'/2.0/rebar/2.0/group/'+id, type:"DELETE", dataType: 'json',
      statusCode: { 200: function(data) { $('#group_'+id).remove(); } }
    });
  }

  function add_group() {
    var group_div = $('#add_group_div');
    var new_group = $('#new_group').val();
    var group = $('th[droptarget="true"]');
    var valid_group_regex = /^[a-zA-Z][a-zA-Z0-9._-]+$/;
    if (new_group.match(valid_group_regex)) {
      // Create the group json and post it
      var group_data = {'name': new_group, 'description': new_group, 'category': 'ui'}
      $.ajax({url:"/2.0/rebar/2.0/group", data:group_data, type:'POST', dataType:'json',
        success:function(data) {
          // on success, add to the UI
          var id = data['id']
          group.attr('id', id);
          group.text(new_group);
          bind_drop($('#'+id.toString()));
          group_div.attr('style', 'display:inline');
          $('a#add_button').attr('class','button');},
        error:function(data) {
          alert("#{t '.add_group_exists'}"); $('a#add_button').attr('class','button'); }
      })}
    else {
      alert("#{t '.add_group_error'}");
      $('a#add_button').attr('class','button');
    }
  }

  function update() {
    // use nopoll parameter for debugging to prevent activity on web server
    // TODO: restore this:
    if (#{params.include?(:nopoll) ? 'false' : 'true'}) {
      $.ajaxSetup({ timeout: 3000 })
      $.getJSON('#{nodes_status_path()}', function(data) {

        // reload path
        var repath = '#{dashboard_path}/'+selected;

        // If node count has changed, re-render the page
        var current_nodes = $('.node').length;
        if(data['count'] != current_nodes) {
          location.href = repath;
        }

        // If node name sum has changed, re-render the page
        if(data['sum'] != #{@sum}) {
          location.href = repath;
        }

        // Update group-level piecharts
        $.each(data['groups'], function(key,val) {
          k = key.toString();
          var values = val['ready'] + ', ' + val['failed'] + ', ' + val['unknown'] + ', ' + (val['building']+val['unready']+val['pending']);
          var total = val['ready']+val['unready']+val['unknown']+val['building']+val['pending']+val['failed'];
          if (groups[k]==undefined) {
            groups[k] = total;
          } else if (groups[k]!=total) {
            location.href =repath;
          }
          $('#group_'+k+' th.status .inline_piechart').html(values).sparkline('html', piechart_options );
          $('#group_'+k+' th.status').attr('title', pie_title(total, val['ready'], val['failed'], val['unknown'], val['building'], val['unready'], val['pending']));
        });

        // Update nodes
        $.each(data['status'], function(key,val) {
          k = key.toString();
          var td = $('#'+k+' td.status');
          var led = td.children('.led');
          if(!(td.attr('raw') === val['raw'])) {
            led.destroy();
            led.attr('class', 'led '+val['status']);
            td.attr('raw', val['raw']);
            td.effect("highlight", {color: '#666666'}, 2000);
            led.attr('title', val['state']);
          }
          // catch the case where we've expanded detail on a node
          s = $('div.container dd.node_state');
          h_key = "head_"+k;
          h = $('div.container div.led[id="'+h_key+'"]');
          if (h.attr('id')==h_key && s.text()!=val['state']) {
            s.text(val['state']);
            s.effect("highlight", {color: '#666666'}, 2000);
            s.attr('title','#{t('raw')}: '+val['raw']);
            var head = $('#head_'+k);
            if (head.length !=0 ) {
              head.destroy();
              head.attr('class', 'led '+val['status']);
              head.attr('title', val['state']);
            }
          }
        });
      });
    }
  }

core/rails/app/views/dashboard/layercake.html.haml
#layercake

  %h1.title= t '.title'
  %div{:style=>"width: auto; padding: 2em;"}
    #leftColumn
      #core{:class=>(@status['core'] || 'ready')}
        = render :partial=>'layercake', :locals=>{ :layer=>'core' }
      #jigs{:class=>(@status['jigs'] || 'ready')}
        = render :partial=>'layercake', :locals=>{ :layer=>'jigs' }

    #rightColumn
      #apps{:class=>(@status['apps'] || 'ready')}
        = render :partial=>'layercake', :locals=>{ :layer=>'apps' }
      #services{:class=>(@status['services'] || 'ready')}
        = render :partial=>'layercake', :locals=>{ :layer=>'services' }
      #clients{:class=>(@status['clients'] || 'ready')}
        = render :partial=>'layercake', :locals=>{ :layer=>'clients' }
      #os{:class=>(@status['is'] || 'ready')}
        = render :partial=>'layercake', :locals=>{ :layer=>'os' }
      #nodes{:class=>(@status['nodes'] || 'ready')}
        = render :partial=>'layercake', :locals=>{ :layer=>'nodes' }
      #network{:class=>(@status['network'] || 'ready')}
        = render :partial=>'layercake', :locals=>{ :layer=>'network' }

.clear


:javascript

  function update() {
    nodes = parseInt($('span#node_count').text());
    if (nodes<#{current_user.settings(:ui).node_refresh}) {
      $.ajaxSetup({ timeout: #{current_user.settings(:ui).refresh} });
        var elasped = parseInt($('span#elapsed_heartbeat').text());
        if (elasped < 3600) {
          location.reload();
        } else {
          console.debug("layercake no refresh: ", elasped);
        }
    }
  }

core/rails/app/views/dashboard/list.html.haml
%p{:style => 'float:right'}
  = select_tag "deployment", options_from_collection_for_select(Deployment.all, "name", "name", params[:deployment]), :id=>"filter"
%h1
  =t '.title'
  -if @deployment
    = link_to @deployment.name, deployment_path(@deployment.id), :title=>@deployment.description
  -else
    = t('all')

- # filter to only show unallocated nodes, with an option to display all
= form_for :dashboard, :'data-remote' => true, :url => '/dashboard/list', :html => { :method=>:put, :'data-type' => 'html',  :id => 'list', :class => "formtastic" } do |f|
  %table.data.box
    %thead
      %tr
        %th= t('.name')
        %th= t('.description')
        %th= t('.deployment')
    %tbody
      - if @nodes and @nodes.count > 0
        - @nodes.sort_by{|n| n.name } #sort nodes by name and by admin
        - admins = @nodes.select{|n| n.admin}.sort_by{|n| n.name }
        - @nodes = admins + (@nodes - admins)
        - @nodes.each do |node|
          %tr.node{ :class => cycle(:odd, :even, :name => "nodes"), :id => node.id }
            %td{:style=>node.admin&&"font-weight: bold;"}
              = text_field_tag "node:#{node.id}:name".to_sym, node.name, :size => 50
            %td= text_field_tag "node:#{node.id}:description".to_sym, "#{node.description || ""}", :size => 50
            %td 
              - deployments = Deployment.all
              = select_tag "node:#{node.id}:deployment_id", options_from_collection_for_select(deployments, "id", "name", node.deployment.id)
      - else
        %tr
          %td{ :colspan=>4 }
            = t 'no_items'

  %input.button{:type => "submit", :name => "submit", :value => t('save')}

.clear

  
:javascript

$(document).ready(function(){
  $("#filter").on("change", function() {
    url = $("#filter").find('option:selected').text();
    console.debug(url);
    window.location.href = "#{(@deployment.nil? ? "list/" : "")}"  +url;
  });
});